version: '3.3'

services:
  event_poller:
    build:
      context: ./event_poller
    container_name: event_poller
    restart: always
    logging:
      driver: awslogs
      options:
        awslogs-group: twitch-bot-logs
        awslogs-region: eu-west-1
        awslogs-stream: event_poller

  eligibility_processor:
    build:
      context: ./eligibility_processor
    container_name: eligibility_processor
    restart: always
    logging:
      driver: awslogs
      options:
        awslogs-group: twitch-bot-logs
        awslogs-region: eu-west-1
        awslogs-stream: eligibility_processor

  action_handler:
    build:
      context: ./action_handler
    container_name: action_handler
    restart: always
    logging:
      driver: awslogs
      options:
        awslogs-group: twitch-bot-logs
        awslogs-region: eu-west-1
        awslogs-stream: action_handler
